sonar.projectKey=lucasfariafr_TP-DevOps
sonar.organization=lucasfariafr
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
